import json,html,shutil,os
from pathlib import Path
ROOT=Path(__file__).parent; S=ROOT; D=ROOT/'dist'; D.mkdir(exist_ok=True)
c=json.loads((S/'config.json').read_text()); esc=html.escape
base=os.environ.get('SITE_BASE_PATH','').rstrip('/')
c['origin']=os.environ.get('SITE_ORIGIN',c['origin'])
for f in ['style.css','app.js','bay.jpg','bay-600.webp','bay-1000.webp','bay-1400.webp']:
 if (S/f).exists(): shutil.copy(S/f,D/f)
manifest=ROOT/'.openai/hosting.json'; 
if manifest.exists():
 m=json.loads(manifest.read_text());m['static']={'directory':'dist'};manifest.write_text(json.dumps(m,indent=2))
nav=[('/about/','About Rob'),('/psychotherapy/','Psychotherapy'),('/aging-memory-caregiving/','Aging & caregiving'),('/fees-faq/','Fees & FAQ')]
def button(label='Schedule a consultation',url='/contact/#consultation',light=False):return f'<a class="button{ " light" if light else ""}" href="{esc(url,quote=True)}">{label}</a>'
def video(index=0):
 v=c['videos'][index]
 title=esc(v['title'],quote=True);label=esc(v.get('label','Meet Rob on video'))
 return f'<div class="video"><button data-video="{esc(v["id"])}" data-start="{v["start"]}" data-title="{title}" aria-label="Load {title} from YouTube">▷ &nbsp; {label}</button></div><p class="video-note">Original video: “{title}.” Loading the player connects to YouTube. <a href="https://www.youtube.com/watch?v={esc(v["id"])}">Watch on YouTube</a>.</p>'
def page(path,title,description,body,cta=True):
 links=''.join(f'<a href="{u}"'+(' aria-current="page"' if path==u else '')+f'>{l}</a>' for u,l in nav)
 canonical=c['origin'].rstrip('/')+path
 schema={'@context':'https://schema.org','@type':'Person','name':c['name'],'jobTitle':'Licensed Marriage and Family Therapist','url':c['origin'],'description':'Psychotherapy for individuals, couples and families in California.'}
 content=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)} | Rob Sarison, LMFT, RDT</title><meta name="description" content="{esc(description,quote=True)}"><meta name="robots" content="{'index,follow' if c['publicLaunch'] else 'noindex,nofollow'}"><link rel="canonical" href="{canonical}"><meta property="og:title" content="{esc(title,quote=True)}"><meta property="og:description" content="{esc(description,quote=True)}"><meta property="og:type" content="website"><meta property="og:url" content="{canonical}"><meta property="og:site_name" content="Rob Sarison Psychotherapy"><meta name="twitter:card" content="summary"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%23153b50'/%3E%3Ctext x='32' y='43' text-anchor='middle' font-family='Georgia' font-size='35' fill='%23f6f4ee'%3ERS%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="/style.css"><script defer src="/app.js"></script><script type="application/ld+json">{json.dumps(schema)}</script></head><body><a class="skip" href="#main">Skip to content</a>{'' if c['publicLaunch'] else '<div class="review-label">Private website preview · Online scheduling is not yet connected</div>'}<header><div class="wrap nav"><a class="brand" href="/" aria-label="Rob Sarison home"><strong>Rob Sarison<span style="color:var(--accent)">.</span></strong><small>Psychotherapy &nbsp; / &nbsp; LMFT, RDT</small></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu</button><nav id="navigation" class="navlinks" aria-label="Main navigation">{links}<a class="portal" href="/client-portal/">Client portal</a>{button('Let’s connect','/contact/')}</nav></div></header><main id="main">{body}</main>'''
 if cta:content+='''<section class="cta"><div class="wrap"><div><p class="eyebrow">A place to begin</p><h2>Let’s talk about what could change.</h2><p>A consultation is a chance to ask questions and see if we’re a good fit.</p></div>'''+button()+'''</div></section>'''
 content+='''<footer><div class="wrap"><div class="top"><div><h3>Rob Sarison, LMFT, RDT</h3><p>Licensed Marriage and Family Therapist<br>Registered Drama Therapist</p><p>San Francisco Bay Area<br>California telehealth</p></div><div><a href="/psychotherapy/">Psychotherapy</a><a href="/aging-memory-caregiving/">Aging, memory loss & family caregiving</a><a href="/drama-therapy/">Drama therapy</a><a href="/training-consultation/">Training & consultation</a></div><div><a href="/about/">About Rob</a><a href="/fees-faq/">Fees & FAQ</a><a href="/contact/">Contact</a><a href="/client-portal/">Client portal</a><a href="/privacy/">Privacy & website information</a></div></div><div class="footnote"><span>© 2026 Rob Sarison. All rights reserved.</span><span>Website inquiries are not monitored for emergencies.</span></div><p>If you are in immediate danger, call 911. For crisis support in the U.S., call or text <a style="display:inline;text-decoration:underline" href="tel:988">988</a> or visit <a style="display:inline;text-decoration:underline" href="https://988lifeline.org/">988 Lifeline</a>.</p></div></footer></body></html>'''
 content=content.replace('San Francisco Bay Area',esc(c['location'])).replace('California telehealth',esc(c['telehealth']))
 if c.get('licenseNumber'):
  content=content.replace('Registered Drama Therapist</p>','Registered Drama Therapist<br>California license '+esc(str(c['licenseNumber']))+'</p>')
 if path=='/contact/':
  contact_details=''
  if c.get('phone'):contact_details+='<p>Phone: '+esc(c['phone'])+'</p>'
  if c.get('email'):contact_details+='<p>Email: <a href="mailto:'+esc(c['email'],quote=True)+'">'+esc(c['email'])+'</a></p>'
  if c.get('officeAddress'):contact_details+='<p>'+esc(c['officeAddress'])+'</p>'
  content=content.replace('<div class="contact-grid">',contact_details+'<div class="contact-grid">')
 content=content.replace('Private website preview · Online scheduling is not yet connected','Website preview · Online scheduling is not yet connected')
 content=content.replace('href="/','href="'+base+'/').replace('src="/','src="'+base+'/').replace('srcset="/','srcset="'+base+'/').replace(', /bay-',', '+base+'/bay-')
 out=D/path.strip('/')/'index.html' if path!='/' else D/'index.html';out.parent.mkdir(parents=True,exist_ok=True);out.write_text(content)
 return path
paths=[]
home='''<div class="wrap"><section class="hero"><div><p class="eyebrow">San Francisco Bay Area · California telehealth</p><h1>Meaningful change.<br><em>Stronger<br>connections.</em></h1><p class="intro"><strong>Psychotherapy and counseling for individuals, couples & families.</strong></p><p class="intro">Warm, direct, and practical therapy to help you understand what keeps repeating—and find a different way forward.</p><div class="actions">'''+button()+'''<a class="textlink" href="/psychotherapy/approach/">Explore my approach ↗</a></div></div><div class="hero-art"><img src="/bay-1000.webp" srcset="/bay-600.webp 600w, /bay-1000.webp 1000w, /bay-1400.webp 1400w" sizes="(max-width:800px) 88vw, 40vw" alt="The Golden Gate Bridge emerging through coastal fog over San Francisco Bay" width="1400" height="1750" fetchpriority="high"><span class="art-caption">A NEW PERSPECTIVE. A PRACTICAL WAY FORWARD.</span></div></section><div class="credential-strip"><span>Licensed Marriage and Family Therapist</span><span>Registered Drama Therapist</span><span>Individual · Couples · Family</span></div></div><section class="section"><div class="wrap"><div class="section-head"><div><p class="eyebrow">Psychotherapy for everyday life</p><h2>What brings you here<br>is where we begin.</h2></div><p>You may know exactly what needs to change. Or you may simply know that something isn’t working. We’ll make sense of it together, with attention to what matters most to you.</p></div><div class="cards">'''
for i,(slug,name,txt) in enumerate([('individual','Individual therapy','For anxiety, low mood, grief, life transitions, and patterns you’re ready to understand and change.'),('couples','Couples therapy','Move beyond the same argument. Work toward clearer communication, greater understanding, and a more connected relationship.'),('family','Family therapy','Make room for different perspectives, address conflict, and navigate changing roles together.')]):home+=f'<article class="card"><span class="number">0{i+1} / WORKING TOGETHER</span><h3>{name}</h3><p>{txt}</p><a class="textlink" href="/psychotherapy/{slug}/">Explore {name.lower()} ↗</a></article>'
home+='''</div></div></section><section class="section dark"><div class="wrap split"><div><p class="eyebrow">The way I work</p><h2>More than an<br>interesting conversation.</h2><p>Therapy should help create meaningful change you can experience in your relationships and everyday life.</p><a class="textlink" href="/psychotherapy/approach/">An active, collaborative approach ↗</a></div><div class="steps"><div class="step"><h3>01 &nbsp; Understand the pattern</h3><p>Notice the connections between your thoughts, emotions, actions, and relationships.</p></div><div class="step"><h3>02 &nbsp; Try something different</h3><p>Draw from CBT, DBT-informed skills, relational work, and creative approaches to practice new responses.</p></div><div class="step"><h3>03 &nbsp; Bring it into your life</h3><p>Set meaningful goals, try practical strategies, and review what is helping. Adjust the work together as your needs change.</p></div></div></div></section><section class="section feature"><div class="wrap split"><div><p class="eyebrow">A particular depth of experience</p><h2>When someone’s memory changes,<br>family life changes too.</h2></div><div><p class="large-copy">Support for the person.<br>Support for the people<br>who love them.</p><p>Aging, memory loss, and caregiving can bring difficult decisions, changing roles, and grief that is hard to name. My background in aging and dementia care informs compassionate, practical support for individuals and families.</p><a class="textlink" href="/aging-memory-caregiving/">Aging, memory loss & family caregiving ↗</a></div></div></section><section class="section"><div class="wrap pair"><article><p class="eyebrow">Creativity with a purpose</p><h2>Sometimes a new perspective needs a different approach.</h2><p>Drama therapy adds imagination, role work, and experiential exercises to the conversation. It is about exploring possibilities—not performing. No acting experience is necessary.</p><a class="textlink" href="/drama-therapy/">What drama therapy can look like ↗</a></article><article><p class="eyebrow">Meet Rob</p><h2>Experience that stays focused on you.</h2><p>I’m Rob Sarison, a Licensed Marriage and Family Therapist and Registered Drama Therapist. My work across psychotherapy, aging services, professional education, and leadership has deepened my interest in how people adapt, connect, and change.</p><a class="textlink" href="/about/">More about Rob ↗</a></article></div></section><section class="section feature"><div class="wrap split"><div><p class="eyebrow">In conversation</p><h2>A sense of the person<br>behind the practice.</h2><p>Meet Rob through an original video from his professional work.</p><a class="textlink" href="/training-consultation/">For professionals: training & consultation ↗</a></div><div>'''+video()+'''</div></div></section>'''
approved_testimonials=[t for t in c.get('testimonials',[]) if t.get('quote') and t.get('attribution') and t.get('context') and ((not t.get('sample') and t.get('permissionToPublish') is True) or (t.get('sample') and not c['publicLaunch']))]
if approved_testimonials:
 home+='<section class="section testimonials"><div class="wrap"><p class="eyebrow">Testimonials</p><h2>Perspectives on working with Rob.</h2>'
 if any(t.get('sample') for t in approved_testimonials):home+='<p class="sample-label"><strong>Staging examples only.</strong> The sample quotes below are fictional and will be replaced with real, approved testimonials before launch.</p>'
 home+='<div class="testimonial-grid">'
 for t in approved_testimonials:
  home+='<figure class="testimonial"><blockquote><p>'+esc(t['quote'])+'</p></blockquote><figcaption>'+esc(t['attribution'])+'<span>'+esc(t['context'])+'</span></figcaption></figure>'
 home+='</div></div></section>'
paths.append(page('/','Psychotherapy and Counseling for Individuals, Couples & Families in California','Practical, collaborative psychotherapy with Rob Sarison, LMFT, RDT. Individuals, couples, families, aging and caregiving. California telehealth.',home))
import runpy
extra_pages=runpy.run_path(str(S/'content.py'))['make_pages'](c,button,video)
polish=runpy.run_path(str(S/'layout.py'))['polish']
for path,title,desc,body in extra_pages:paths.append(page(path,title,desc,polish(body)))
(D/'robots.txt').write_text('User-agent: *\n'+('Allow: /\nSitemap: '+c['origin']+'/sitemap.xml\n' if c['publicLaunch'] else 'Disallow: /\n'))
(D/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+c['origin']+p+'</loc></url>' for p in paths)+'</urlset>')
print('Built',len(paths),'pages')
